-- 创建数据库 springdemo2024
DROP DATABASE IF EXISTS springdemo2024;
CREATE DATABASE springdemo2024;
USE springdemo2024;

-- 创建用户信息表
DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INT AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL COMMENT '姓名',
  password VARCHAR(50) DEFAULT NULL COMMENT '密码',
  email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 COMMENT='用户信息表';